### ISSUE TITLE
pre-processing 

### ISSUE THREAD

**Issue by macd2** [nagypeterjob/Sentiment-Analysis-NLTK-ML#2]
Hello,
is by any chance also the script to create the .csv file available? 
thanks

**Comment by nagypeterjob** [comment]
I don't know what you mean by creating the csv. But the original dataset can be found on Kaggle:
https://www.kaggle.com/ngyptr/python-nltk-sentiment-analysis

**Comment by macd2** [comment]
Thanks for the answer, 
yes i know, but i want to create a custom dataset so there for it would be handy to have the script that created the your dataset.

**Comment by nagypeterjob** [comment]
Then again, I did not create a custom dataset. I used an existing one from Kaggle. I do not possess the script you are talking about, so I cannot help.

**Comment by macd2** [comment]
alright thanks than!
